server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.3.18:3306/guli_pms?serverTimezone=Asia/Shanghai
    url: jdbc:mysql://192.168.3.18:3306/guli_pms
    username: root
    password: root
  redis:
    host: 192.168.160.100
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/pms/**/*.xml
logging:
  level:
    com:
      atguigu: info